mysite.Auth/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

mysite.Auth/polls/urls.py
from django.conf.urls import patterns, url
from polls import views
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'polls/login.html'}, name='login'),
)

mysite.Auth/polls/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite.Auth/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from polls.models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        """Return the last five published polls."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/result.html'

from django.contrib.auth.decorators import login_required

@login_required(login_url='/polls/login')
def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/result.html', {'question': question})

mysite.Auth/polls/templates/polls/detail.html
<html>
<body>

<h1>{{ question.question_text }}</h1>

Welcome <B>
{% if user.is_authenticated %}
{{ user.get_username }}
<p>
{% else %}
<a href="{% url 'polls:login' %}?next=/polls">Guest</a>
{% endif %}
</B>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
</body>
</html>

mysite.Auth/polls/templates/polls/index.html
<HTML>
<body>
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <!--Static a href="/polls/{{ poll.id }}/">{{ poll.question_text }}</a-->
        <!--URLName a href="{ % url 'detail' poll.id % }">{{ poll.question_text }}</a-->
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</HTML>

mysite.Auth/polls/templates/polls/login.html
<HTML>
<body>
{% block login %}

{% if user.is_authenticated %}
Welcome {{ user.get_username }}
{% else %}

	{% if form.errors %}
	<p>Your username and password didn't match. Please try again.</p>
	{% endif %}

	<form method="post" action="{% url 'polls:django.contrib.auth.views.login' %}">
	{% csrf_token %}
	<table>
	<tr>
	    <td>{{ form.username.label_tag }}</td>
	    <td>{{ form.username }}</td>
	</tr>
	<tr>
	    <td>{{ form.password.label_tag }}</td>
	    <td>{{ form.password }}</td>
	</tr>
	</table>

	<input type="submit" value="login" />
	<input type="hidden" name="next" value="{{ next }}" />
	</form>
{% endif %}

{% endblock %}
</body>
</HTML>

mysite.Auth/polls/templates/polls/result.html
<HTML>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</HTML>